name: API Docs

on:
  release:
    types: [published]

jobs:
  api-docs:
    runs-on: macos-latest
    env:
      MODULE_NAME: "Currency"
      REPO_URL: "https://github.com/peek-travel/swift-currency"
    steps:
      - uses: actions/checkout@v1
      - name: "Install Jazzy"
        run: gem install jazzy
      - name: "Generate API Docs"
        run: |
          export VERSION=$(git describe --abbrev=0 --tags || echo "0.0.0")
          swift build
          jazzy --clean \
                --author "Peek Travel, Inc" \
                --readme "./README.md" \
                --author_url "https://github.com/peek-travel" \
                --github_url "$REPO_URL" \
                --github-file-prefix "$REPO_URL/blob/$VERSION" \
                --root-url "https://peek-travel.gitlab.io/swift-currency/" \
                --module "$MODULE_NAME" \
                --module-version "$VERSION" \
                --theme apple \
                --swift-build-tool spm \
                --build-tool-arguments -Xswiftc,-swift-version,-Xswiftc,5 \
                --output "./public"
      - name: "Deploy Docs"
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }} 
          publish_dir: ./public
          user_name: "peek-opensource"
          user_email: "dev-noreply@peek.com"
